{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "node_js": [
    "stable"
  ],
  "notifications": {
    "email": [
      {
        "enabled": false
      }
    ]
  },
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "script": [
    "npm run build"
  ],
  "deploy": [
    {
      "provider": "pages",
      "strategy": "git",
      "skip_cleanup": true,
      "local_dir": "build",
      "on": {
        "branch": [
          "master"
        ]
      },
      "token": "travis"
    }
  ]
}
